// Copies the legal drafts in docs/legal into the app bundle.
// Run `pnpm gen:legal` after editing a draft; a test fails if this file is stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const docsDir = join(here, '../../../docs/legal');
const out = join(here, '../src/features/legal/content.generated.ts');

const files = {
  privacy: 'privacy-policy.md',
  terms: 'terms-of-service.md',
  disclaimer: 'medical-disclaimer.md',
};

const body = Object.entries(files)
  .map(([id, file]) => `  ${id}: ${JSON.stringify(readFileSync(join(docsDir, file), 'utf8'))},`)
  .join('\n');

writeFileSync(
  out,
  `// Generated by scripts/gen-legal.mjs from docs/legal. Do not edit.\nexport const legalDocs = {\n${body}\n} as const;\n`,
);
